### PR TITLE
Inital work on basic function of tar finding script

### PR DESCRIPTION
**Pull request by Jsims0**
Initial pass on script to find .tar files older than a period of time with a start on some accompanying tests

basic features included:
- Takes in command line arguments of a file containing a DNAnexus token, a DNA project id, output destination.
- DNAnexus token login
- Finds files in a given DNAnexus project(via project id) that match the regex criteria `"^run.*.tar.gz$"` and 
are older than the specified time.
- Extracts the DNAnexus file name, file id and project id of each file found and outputs to a file.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @Jsims0)

___
*[`main.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5COa54UOddqA5cXn7:-OB5COa54UOddqA5cXn8:bdbmop1) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L12)):*
> ```Python
> 
> 
> ##dx login
> ```

I assume these and the `#imports` aren't needed above and can be cleaned up? 



_Code quote:_
```Python
# functions


##dx login
```
___
*[`main.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5D3Qv1JGBPLoir5tW:-OB5D3Qv1JGBPLoir5tX:b8l9pnl) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L41)):*
> ```Python
>         print(dx.api.system_whoami())
>     except dx.exceptions.InvalidAuthentication as err:
>         print(err)
> ```

here you either want to re-raise the error, or handle it some other way as currently if the token is not valid this function will just return None and continue from where it is called



_Code quote:_
```Python
print(err)
```
___
*[`main.py` line 105 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5Daz93utdC0GUcVRy:-OB5Daz93utdC0GUcVRz:b-wq6f1a) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L105)):*
what is it here you're trying to get? is it the timedelta of `n` months back?

if so you can do it with the following:
```
>>> from datetime import datetime
>>> from dateutil.relativedelta import relativedelta
>>> datetime.now() - relativedelta(months=6)
datetime.datetime(2024, 5, 7, 10, 49, 11, 96848)
```

For dx query times, you can divide by 1000 then treat this as a datetime object too like here: https://github.com/eastgenomics/themis/blob/6990f8b49759b8abc60822a42baaec56d802a5f6/TAT_audit/utils/dx_requests.py#L326



_Code quote:_
```Python
##get date for deletion(6 months ago)
### TODO: need a better way of adjusting this
def get_time_limit() -> int:
    """a method to get a timestamp in unix milliseconds


    Returns:
        int: unix epoch time in miliseconds
    """
    # 15778458 is 6 months in seconds, dx uses unix epoch in milliseconds
    # 86400 ia 1 day
    return round(time.time() - 86400) * 1000
```
___
*[`main.py` line 109 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5EqxaE2tfhhCxVqoQ:-OB5EqxaE2tfhhCxVqoR:b-jwb8h7) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L109)):*
> ```Python
> 
> # inputs
> ## argumets or read from config?
> ```

I would vote a config if this is something we are going to leave running on a cron, most of ours tend to be JSON but feel free to use YAML/TOML/INI etc (although my preference is JSON if it gets more complex).

Example of some bigger configs that we have are for things like eggd_dias_batch and eggd_conductor, which are stored here if you want to take a look:
- https://github.com/eastgenomics/eggd_conductor_configs/tree/main/assay_configs
- https://github.com/eastgenomics/egg5_dias_CEN_config/blob/main/dias_CEN_config_GRCh37_v3.2.0.json 



_Code quote:_
```Python
# inputs
## argumets or read from config?
```
___
*[`tests/tests.py` line 9 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5GV3hBwyxowNTRU4_:-OB5GV3i7zJXA4lML3Hj:b-yk59gp) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/tests/tests.py#L9)):*
> ```Python
> 
> 
> class TestDeletionMethods(unittest.TestCase):
> ```

I'm not sure if it is the _best_ way, but I have gone for generally having one class per tested function and naming it the same (i.e. `foo_does_bar()` would be `class TestFooDoesBar()`), I find this much easier to go between my tests and code and see what is testing what. For really small functions I sometimes just have a single test fucnction without a class and have a few subtests inside 



_Code quote:_
```Python
TestDeletionMethods
```
___
*[`tests/tests.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5FinnBjxXuuMqR96M:-OB5FinnBjxXuuMqR96N:b-o4otqh) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/tests/tests.py#L13)):*
> ```Python
>     def test_get_time_limit(self):
>         limit = get_time_limit()
>         assert type(limit) is int()
> ```

since you're using class tests with `unittest.TestCase`, you can use things like `self.assertIsInstance(limit, int)` which tends to give nicer error messages and is very flexible.

If you want some examples there's a load of tests here that I've just done: https://github.com/eastgenomics/s3_upload/tree/main/tests



_Code quote:_
```Python
assert type(limit) is int()
```
___
*[`tests/tests.py` line 21 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5Gvg83Ys0EL6H-UOq:-OB5Gvg83Ys0EL6H-UOr:b1v1zhj) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/tests/tests.py#L21)):*
> ```Python
> 
>     @patch("main.dx.api.system_find_data_objects")
>     def test_find_files(self, mock_find):
> ```

I would try and make your test names as verbose and specific as possible, it makes it a lot easier to understand what is being tested in the test case and more obvious when loads fail (have a look through some recent repos like the s3_upload and bulk_reanalysis etc for inspiration)



_Code quote:_
```Python
test_find_files
```

**Review by Jsims0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5COa54UOddqA5cXn7:-OB67T6NEpk8OBFTXK47:b5o2oll) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L12)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I assume these and the `#imports` aren't needed above and can be cleaned up?
</blockquote></details>

yeah, it's left over from planning out the script
___
*[`main.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5D3Qv1JGBPLoir5tW:-OB67ns09s2t17JhJ3rr:b-kqfr0y) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L41)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

here you either want to re-raise the error, or handle it some other way as currently if the token is not valid this function will just return None and continue from where it is called
</blockquote></details>

good point, i'll raise an appropriate error
___
*[`main.py` line 105 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5Daz93utdC0GUcVRy:-OB67ybY67iqVTMx0gnS:bcjnu9a) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L105)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is it here you're trying to get? is it the timedelta of `n` months back?

if so you can do it with the following:
```
>>> from datetime import datetime
>>> from dateutil.relativedelta import relativedelta
>>> datetime.now() - relativedelta(months=6)
datetime.datetime(2024, 5, 7, 10, 49, 11, 96848)
```

For dx query times, you can divide by 1000 then treat this as a datetime object too like here: https://github.com/eastgenomics/themis/blob/6990f8b49759b8abc60822a42baaec56d802a5f6/TAT_audit/utils/dx_requests.py#L326
</blockquote></details>

I think yes, I just need the unix epoch timestamp for n months ago. I'll look into your suggested alternative method.
___
*[`main.py` line 109 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5EqxaE2tfhhCxVqoQ:-OB68YWHBj1MYQ_8W5Lg:b-r2ftga) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L109)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I would vote a config if this is something we are going to leave running on a cron, most of ours tend to be JSON but feel free to use YAML/TOML/INI etc (although my preference is JSON if it gets more complex).

Example of some bigger configs that we have are for things like eggd_dias_batch and eggd_conductor, which are stored here if you want to take a look:
- https://github.com/eastgenomics/eggd_conductor_configs/tree/main/assay_configs
- https://github.com/eastgenomics/egg5_dias_CEN_config/blob/main/dias_CEN_config_GRCh37_v3.2.0.json
</blockquote></details>

ok, i'll leave the introduction of configs for a feature branch?
___
*[`tests/tests.py` line 9 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5GV3hBwyxowNTRU4_:-OB68z49ErZRrKYk1_yV:b-a732rp) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/tests/tests.py#L9)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'm not sure if it is the _best_ way, but I have gone for generally having one class per tested function and naming it the same (i.e. `foo_does_bar()` would be `class TestFooDoesBar()`), I find this much easier to go between my tests and code and see what is testing what. For really small functions I sometimes just have a single test fucnction without a class and have a few subtests inside
</blockquote></details>

I can change it to doing it as you suggest, no problem. I think I have in the past had a test class per feature/function(not meaning methods) of the script. 
___
*[`tests/tests.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5FinnBjxXuuMqR96M:-OB69aLDBRdP52DYeoFh:b7fprhh) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/tests/tests.py#L13)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

since you're using class tests with `unittest.TestCase`, you can use things like `self.assertIsInstance(limit, int)` which tends to give nicer error messages and is very flexible.

If you want some examples there's a load of tests here that I've just done: https://github.com/eastgenomics/s3_upload/tree/main/tests
</blockquote></details>

yeah, If I had thought about this more I probably would have thought to use `assertIsInstance`
___
*[`tests/tests.py` line 21 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5Gvg83Ys0EL6H-UOq:-OB69v_S9DN8nik5BZ42:bb2v4ia) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/tests/tests.py#L21)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I would try and make your test names as verbose and specific as possible, it makes it a lot easier to understand what is being tested in the test case and more obvious when loads fail (have a look through some recent repos like the s3_upload and bulk_reanalysis etc for inspiration)
</blockquote></details>

I can rename them no problem. they are just using the names of the functions in the main script

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @Jsims0)

___
*[`main.py` line 109 at r1](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OB5EqxaE2tfhhCxVqoQ:-OCIrRli7MN74pWHQtga:bobw8wx) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/c198a9991723be500664bff5cf8f0d04a61db4af/main.py#L109)):*
<details><summary><i>Previously, Jsims0 wrote…</i></summary><blockquote>

ok, i'll leave the introduction of configs for a feature branch?
</blockquote></details>

sure that's fine
___
*[`main.py` line 24 at r2](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OCIq1EZ2_Pb4Q2mIO2W:-OCIq1E_54IDwyWXM_Cs:b571nlg) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/2752438bbcf3a8cf515556549756cc7f4de5c03f/main.py#L24)):*
> ```Python
>         AUTH_TOKEN = file.read().rstrip()
> 
>     return AUTH_TOKEN
> ```

this is nitpicky, but variables should stick to being lower case unless you're defining them at the module level as globals. In Python there's no immutable constants, but convention is anything defined in upper case is a constant that is in the global scope.

tiny bit from pep8 on this: https://peps.python.org/pep-0008/#constants

generally I'd limit globals to things like keys you don't want to pass around / have to pull from a file, or where they are coming from the module `__init__.py` and then imported from there:
- https://github.com/eastgenomics/s3_upload/blob/86071c624bcbed2be3fc656928201ce83ecb1f77/scripts/benchmark.py#L21
- https://github.com/eastgenomics/s3_upload/blob/main/tests/e2e/__init__.py



_Code quote:_
```Python
    with open(f"{path}", "r") as file:
        AUTH_TOKEN = file.read().rstrip()

    return AUTH_TOKEN
```
___
*[`main.py` line 63 at r2](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OCIr3RTC2ZfB39lMEpL:-OCIr3RTC2ZfB39lMEpM:bybyovw) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/2752438bbcf3a8cf515556549756cc7f4de5c03f/main.py#L63)):*
> ```Python
>             "scope": {"project": project},
>             "folder": "/",
>             "describe": True,
> ```

consider limiting this to what you want in the describe details to reduce response size, and also if you want to use this directly vs `dxpy.find_data_objects`



_Code quote:_
```Python
"describe": True,
```
___
*[`tests/tests.py` line 12 at r2](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OCIrb5CB6SD-qXS_-gT:-OCIrb5CB6SD-qXS_-gU:bb7phvt) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/2752438bbcf3a8cf515556549756cc7f4de5c03f/tests/tests.py#L12)):*
> ```Python
> class TestGetTimeLimit(unittest.TestCase):
> 
>     def test_time_is_itn(self):
> ```

typo



_Code quote:_
```Python
itn
```

**Review by Jsims0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 24 at r2](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OCIq1EZ2_Pb4Q2mIO2W:-OCYgK5P70CBPeuflpo4:b-896fix) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/2752438bbcf3a8cf515556549756cc7f4de5c03f/main.py#L24)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this is nitpicky, but variables should stick to being lower case unless you're defining them at the module level as globals. In Python there's no immutable constants, but convention is anything defined in upper case is a constant that is in the global scope.

tiny bit from pep8 on this: https://peps.python.org/pep-0008/#constants

generally I'd limit globals to things like keys you don't want to pass around / have to pull from a file, or where they are coming from the module `__init__.py` and then imported from there:
- https://github.com/eastgenomics/s3_upload/blob/86071c624bcbed2be3fc656928201ce83ecb1f77/scripts/benchmark.py#L21
- https://github.com/eastgenomics/s3_upload/blob/main/tests/e2e/__init__.py
</blockquote></details>

Done.
___
*[`main.py` line 63 at r2](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1#-OCIr3RTC2ZfB39lMEpL:-OCYgD87D6c1DaIDeN2v:b-896fix) ([raw file](https://github.com/eastgenomics/NGS_Tar_deletion/blob/2752438bbcf3a8cf515556549756cc7f4de5c03f/main.py#L63)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

consider limiting this to what you want in the describe details to reduce response size, and also if you want to use this directly vs `dxpy.find_data_objects`
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Jsims0)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/NGS_Tar_deletion/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Jsims0)

**Pull request merged**
